package io.bunnycal.session.domain;

import io.bunnycal.common.audit.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "event_sessions",
        indexes = {
            @Index(name = "idx_event_sessions_host_start", columnList = "host_id, start_time"),
            @Index(name = "idx_event_sessions_event_type", columnList = "event_type_id")
        })
public class EventSession extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "host_id", nullable = false)
    private UUID hostId;

    @Column(name = "event_type_id", nullable = false)
    private UUID eventTypeId;

    @Column(name = "start_time", nullable = false)
    private Instant startTime;

    @Column(name = "end_time", nullable = false)
    private Instant endTime;

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 16)
    private SessionStatus status = SessionStatus.OPEN;

    @Column(name = "capacity", nullable = false)
    private int capacity;

    @Builder.Default
    @Column(name = "confirmed_count", nullable = false)
    private int confirmedCount = 0;

    @Builder.Default
    @Column(name = "version", nullable = false)
    private long version = 0L;

    @Builder.Default
    @Column(name = "calendar_sequence", nullable = false)
    private long calendarSequence = 0L;

    @Builder.Default
    @Column(name = "terminal_intent_epoch", nullable = false)
    private long terminalIntentEpoch = 0L;

    /**
     * The reservation window that generated this session.
     *
     * <p><b>Write-once.</b> Set exactly once, when the session is first materialized
     * in {@code SessionService.findOrCreateSession}. It records the rule that
     * <em>created</em> the occurrence, not the rule that currently governs it — a
     * session moved three times still traces back to its origin. Rescheduling and
     * rule edits must never rewrite it.
     *
     * <p>Null for sessions predating lineage tracking and for ad-hoc sessions the
     * host created directly, which never had a generating rule.
     */
    @Column(name = "reservation_window_id", updatable = false)
    private UUID reservationWindowId;

    /**
     * Where the recurrence rule originally placed this occurrence.
     *
     * <p><b>Write-once.</b> {@link #startTime} is where the session actually is and
     * moves whenever the host reschedules; this is where the rule said it should be
     * and never changes. Keeping both means "which Monday was this?" is answerable
     * directly rather than by replaying reschedule history.
     *
     * <p>Null under the same conditions as {@link #reservationWindowId}.
     */
    @Column(name = "scheduled_occurrence_start", updatable = false)
    private Instant scheduledOccurrenceStart;

    /**
     * When this session stopped following its rule's schedule. Null while the session
     * still tracks the recurrence rule.
     */
    @Column(name = "detached_at")
    private Instant detachedAt;

    /**
     * Why this session detached. Always set together with {@link #detachedAt}
     * (enforced by a DB check constraint).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "detached_reason", length = 32)
    private SessionDetachedReason detachedReason;

    /**
     * Whether the vacated occurrence still blocks the host's <em>other</em> event types.
     *
     * <p>Only meaningful once a session has moved off its origin. It does not govern whether
     * the occurrence itself is consumed — that is unconditional: a moved occurrence is never
     * regenerated by its own recurrence rule, whatever this flag says. Moving a class does not
     * schedule a second one in the slot it left.
     *
     * <p>Defaults true, which is the safe reading of a reschedule: the host moved the session
     * because they are unavailable at the original time, so that hour stays protected. Clearing
     * it is an explicit opt-in that reopens the hour to 1:1, round robin, collective and other
     * group events.
     */
    @Builder.Default
    @Column(name = "origin_blocks_other_events", nullable = false)
    private boolean originBlocksOtherEvents = true;
}
