package io.bunnycal.session.domain;

/**
 * Why an {@link EventSession} stopped following its reservation window's schedule.
 *
 * <p>Recorded explicitly rather than inferred: six months later, support and
 * analytics can answer "why is this session detached?" without reconstructing it
 * from surrounding history.
 */
public enum SessionDetachedReason {

    /** The host moved this single occurrence to a different time. */
    HOST_RESCHEDULED,

    /**
     * The recurrence rule changed underneath a session that already had bookings.
     * The session is pinned at its original time so guests are never silently moved;
     * future occurrences follow the new rule.
     */
    RULE_CHANGED,

    /** The host deliberately placed this session outside their normal availability. */
    HOST_OVERRIDE,

    /**
     * An ad-hoc session created directly by the host, never generated by a rule
     * (e.g. one extra workshop alongside a weekly series).
     */
    MANUAL_SESSION
}
