management:
  otlp:
    metrics:
      export:
        enabled: false

calendar:
  webhook:
    enabled: false
    provider:
      google:
        enabled: false
      microsoft:
        enabled: false
