spring:
  application:
    name: easySchedule

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics   # change to http://otel-collector:4318 if app runs in Docker
        step: 10s
        connect-timeout: 2s
        read-timeout: 5s

  metrics:
    export:
      otlp:
        enabled: true
    tags:
      application: ${spring.application.name}

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

jwt:
  secret: ${JWT_SECRET:my-super-long-secret-key-which-is-at-least-32-characters}
  expiration: ${JWT_EXPIRATION:3600000}

auth:
  refresh-token:
    bytes: ${REFRESH_TOKEN_BYTES:48}
    ttl-days: ${REFRESH_TOKEN_TTL_DAYS:1}