package io.bunnycal.session.service;

import io.bunnycal.common.time.TimeSource;
import io.bunnycal.session.domain.EventSession;
import io.bunnycal.session.domain.SessionDetachedReason;
import io.bunnycal.session.repository.EventSessionRepository;
import java.util.List;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Pins booked sessions in place when the recurrence rule that generated them changes.
 *
 * <p>The alternative — moving them with the rule — silently relocates guests who already
 * hold a seat, which is the behavior most scheduling products deliberately avoid. Pinning
 * keeps existing bookings exactly where they were promised while future occurrences
 * follow the new rule, and surfaces the divergence to the host so they can resolve it
 * deliberately.
 *
 * <p>Lives in {@code session} rather than {@code availability} so the availability
 * service depends on this one-way rather than the two packages depending on each other.
 */
@Service
public class SessionPinningService {

    private static final Logger log = LoggerFactory.getLogger(SessionPinningService.class);

    private final EventSessionRepository sessionRepository;
    private final TimeSource timeSource;

    public SessionPinningService(EventSessionRepository sessionRepository, TimeSource timeSource) {
        this.sessionRepository = sessionRepository;
        this.timeSource = timeSource;
    }

    /**
     * Detaches every booked future session generated by the given windows.
     *
     * <p>Called before a window is updated or retired. Sessions are not moved and their
     * bookings are untouched — only their relationship to the rule changes, so the rule
     * can be rewritten without dragging guests along.
     *
     * @return the sessions that were pinned by this call
     */
    @Transactional
    public List<EventSession> pinBookedSessions(UUID eventTypeId, List<UUID> windowIds) {
        if (windowIds == null || windowIds.isEmpty()) {
            return List.of();
        }
        List<EventSession> booked = sessionRepository.findBookedFutureSessionsForWindows(
                eventTypeId, windowIds, timeSource.now());
        if (booked.isEmpty()) {
            return List.of();
        }
        for (EventSession session : booked) {
            sessionRepository.markDetached(session.getId(), timeSource.now(),
                    SessionDetachedReason.RULE_CHANGED.name());
        }
        log.info("session_pinned_on_rule_change eventTypeId={} count={} sessionIds={}",
                eventTypeId, booked.size(), booked.stream().map(EventSession::getId).toList());
        return booked;
    }
}
