-- Session ↔ Reservation Window Lineage
--
-- Establishes durable identity between a recurrence rule and the sessions it
-- generated, so that editing a rule can leave already-booked sessions pinned in
-- place rather than silently moving guests.
--
-- Two problems are solved here:
--
--   1. Window identity. replaceWindows() previously deleted every row for an
--      event type and re-inserted, destroying window IDs on every edit. Nothing
--      linked a session back to the rule that produced it, so after an edit it
--      was impossible to tell which sessions belonged to the old rule. Windows
--      are now updated in place (keyed by client-supplied id) and retired rather
--      than deleted.
--
--   2. Occurrence identity. A session's start_time moves when a host reschedules
--      it. scheduled_occurrence_start records where the recurrence rule originally
--      placed the occurrence and never changes, so "which Monday was this?" is
--      answerable without replaying history.
--
-- Both lineage columns are write-once by contract (enforced in SessionService and
-- documented on EventSession). Nullable throughout: rows predating this migration
-- have no lineage, and host-created ad-hoc sessions legitimately never will.

-- ── Session lineage ────────────────────────────────────────────────────────────

ALTER TABLE event_sessions
    ADD COLUMN reservation_window_id      UUID,
    ADD COLUMN scheduled_occurrence_start TIMESTAMPTZ,
    ADD COLUMN detached_at                TIMESTAMPTZ,
    ADD COLUMN detached_reason            VARCHAR(32);

-- ON DELETE SET NULL rather than CASCADE: losing a window must never destroy the
-- sessions (and their bookings) it generated. In practice windows are retired
-- rather than deleted, so this is a backstop.
ALTER TABLE event_sessions
    ADD CONSTRAINT fk_event_sessions_reservation_window
        FOREIGN KEY (reservation_window_id)
        REFERENCES group_event_reservation_windows (id)
        ON DELETE SET NULL;

-- Why a session left its rule's schedule -- recorded explicitly so support and
-- analytics never have to infer it from surrounding history.
--   HOST_RESCHEDULED : host moved this single occurrence
--   RULE_CHANGED     : the recurrence rule changed underneath a booked session
--   HOST_OVERRIDE    : host forced a time outside normal availability
--   MANUAL_SESSION   : ad-hoc session, never generated by a rule
ALTER TABLE event_sessions
    ADD CONSTRAINT ck_event_sessions_detached_reason
        CHECK (detached_reason IN (
            'HOST_RESCHEDULED',
            'RULE_CHANGED',
            'HOST_OVERRIDE',
            'MANUAL_SESSION'
        ));

-- detached_at and detached_reason are set together or not at all.
ALTER TABLE event_sessions
    ADD CONSTRAINT ck_event_sessions_detached_pairing
        CHECK ((detached_at IS NULL) = (detached_reason IS NULL));

-- Supports "which live sessions did this rule generate?" -- the lookup behind
-- pinning on rule edit and the pinned-session listing.
CREATE INDEX idx_event_sessions_window_attached
    ON event_sessions (reservation_window_id)
    WHERE detached_at IS NULL;

-- ── Window lifecycle ───────────────────────────────────────────────────────────
--
-- RETIRED means historical: the window no longer generates slots but is preserved
-- so pinned sessions keep resolvable lineage. Storage cost is trivial next to the
-- audit, support, and analytics value.
--
-- Deliberately NOT overloaded for temporary pauses. A future "rule paused, keep
-- it" state (teacher on leave) should be added as a distinct DISABLED value; the
-- check constraint is written to be extended.

ALTER TABLE group_event_reservation_windows
    ADD COLUMN status     VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN retired_at TIMESTAMPTZ;

ALTER TABLE group_event_reservation_windows
    ADD CONSTRAINT ck_gerw_status
        CHECK (status IN ('ACTIVE', 'RETIRED'));

ALTER TABLE group_event_reservation_windows
    ADD CONSTRAINT ck_gerw_retired_pairing
        CHECK ((status = 'RETIRED') = (retired_at IS NOT NULL));

-- Every slot-generation read filters on status; all existing rows are ACTIVE.
CREATE INDEX idx_gerw_event_type_active
    ON group_event_reservation_windows (event_type_id)
    WHERE status = 'ACTIVE';
