package io.bunnycal.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", "An unexpected internal server error occurred."),
    VALIDATION_ERROR("VALIDATION_ERROR", "Request validation failed."),
    UNAUTHORIZED("UNAUTHORIZED", "Authentication is required."),
    FORBIDDEN("FORBIDDEN", "You do not have permission to access this resource."),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", "Requested resource was not found."),
    OAUTH_EMAIL_MISSING("OAUTH_EMAIL_MISSING", "OAuth provider did not return an email."),
    INVALID_TIMEZONE("INVALID_TIMEZONE", "Timezone is invalid."),
    TOKEN_EXPIRED("TOKEN_EXPIRED", "Token has expired."),
    TOKEN_INVALID("TOKEN_INVALID", "Token is invalid."),
    OAUTH_INVALID_RESPONSE("OAUTH_INVALID_RESPONSE", "Oauth response is invalid"),
    IDEMPOTENCY_KEY_REQUIRED("IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key header is required."),
    IDEMPOTENCY_HASH_MISMATCH("IDEMPOTENCY_HASH_MISMATCH",
            "Idempotency-Key was previously used with a different request payload."),
    IDEMPOTENCY_IN_PROGRESS("IDEMPOTENCY_IN_PROGRESS",
            "A request with this Idempotency-Key is still being processed. Retry shortly."),
    IDEMPOTENCY_RACE("IDEMPOTENCY_RACE",
            "Idempotency-Key was reaped during processing. Retry with a new key."),
    IDEMPOTENCY_RESPONSE_TOO_LARGE("IDEMPOTENCY_RESPONSE_TOO_LARGE",
            "Response too large to cache for idempotency replay."),
    SLOT_ALREADY_BOOKED("SLOT_ALREADY_BOOKED",
            "Requested time overlaps an existing booking for this host."),
    SLOT_UNAVAILABLE("SLOT_UNAVAILABLE",
            "This time slot is no longer available."),
    GOOGLE_EVENT_CREATION_FAILED("GOOGLE_EVENT_CREATION_FAILED",
            "Unable to create Google Calendar event."),
    CALENDAR_SYNC_IN_PROGRESS("CALENDAR_SYNC_IN_PROGRESS",
            "Calendar synchronization is still in progress."),
    TOO_MANY_PENDING_BOOKINGS("TOO_MANY_PENDING_BOOKINGS",
            "Too many pending bookings overlap this time window. Try again later."),
    INVALID_STATE_TRANSITION("INVALID_STATE_TRANSITION",
            "Booking is not in the expected state or version — concurrent update may have occurred."),
    CONFERENCING_DISCONNECT_NOT_SUPPORTED("CONFERENCING_DISCONNECT_NOT_SUPPORTED",
            "This conferencing provider cannot be disconnected on its own."),
    GROUP_ATTENDEE_RESCHEDULE_NOT_SUPPORTED("GROUP_ATTENDEE_RESCHEDULE_NOT_SUPPORTED",
            "Group event attendees cannot reschedule. Cancel your registration and re-book."),
    SESSION_CAPACITY_FULL("SESSION_CAPACITY_FULL",
            "This session is fully booked. No seats are available."),
    SESSION_CANCELLED("SESSION_CANCELLED",
            "This session has been cancelled."),
    ALREADY_REGISTERED("ALREADY_REGISTERED",
            "You are already registered for this session."),
    REGISTRATION_HOLD_ACTIVE("REGISTRATION_HOLD_ACTIVE",
            "Your registration is currently being held."),
    REGISTRATION_EXPIRED("REGISTRATION_EXPIRED",
            "Your registration hold has expired. Please start over."),
    TEAM_SLUG_TAKEN("TEAM_SLUG_TAKEN",
            "A team with this slug already exists for this owner."),
    TEAM_MEMBER_ALREADY_EXISTS("TEAM_MEMBER_ALREADY_EXISTS",
            "This user is already a member of the team."),
    TEAM_INVITATION_ALREADY_PENDING("TEAM_INVITATION_ALREADY_PENDING",
            "A pending invitation already exists for this email on this team."),
    TEAM_INVITATION_INVALID("TEAM_INVITATION_INVALID",
            "Invitation is invalid, expired, or already used."),
    TEAM_INVITATION_EMAIL_MISMATCH("TEAM_INVITATION_EMAIL_MISMATCH",
            "This invitation was issued to a different email address."),
    TEAM_OWNER_REQUIRED("TEAM_OWNER_REQUIRED",
            "Only the team owner can perform this action."),
    TEAM_LAST_OWNER("TEAM_LAST_OWNER",
            "A team must always have exactly one owner."),
    PARTICIPANTS_REQUIRED("PARTICIPANTS_REQUIRED",
            "This event type requires at least one participant."),
    PARTICIPANTS_NOT_ALLOWED_FOR_KIND("PARTICIPANTS_NOT_ALLOWED_FOR_KIND",
            "This event kind is single-host and cannot have additional participants."),
    PARTICIPANT_NOT_IN_TEAM("PARTICIPANT_NOT_IN_TEAM",
            "Participant is not a member of any of your teams."),
    HOST_NOT_SCHEDULABLE("HOST_NOT_SCHEDULABLE",
            "This host is not available for scheduling."),
    EVENT_TYPE_NOT_PUBLISHED("EVENT_TYPE_NOT_PUBLISHED",
            "This event type is not currently accepting bookings."),
    UNPUBLISHABLE_EVENT_TYPE("UNPUBLISHABLE_EVENT_TYPE",
            "This event type cannot be published until all participants are ready.");

    private final String code;
    private final String message;
}
